openapi: 3.0.3
info:
  title: Akismet API
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/CHRIS_60/Akismet/1.0.0
  - url: https://rest.akismet.com/1.1
externalDocs:
  description: Akismet Developer Documentation
  url: https://akismet.com/developers
paths:
  /verify-key:
    post:
      summary: Verify Akismet API Key
      description: |
        Verifies the provided Akismet API key to check its validity and ensure it can be used for API requests.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                key:
                  type: string
                blog:
                  type: string
              required:
                - key
                - blog
      responses:
        '200':
          description: Key verification successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    description: Indicates if the key is valid or not.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the encountered error.
      tags:
        - Key Verification